coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%

ignore:
  # ignore test frameworks
  - "openmls/tests/utils/managed_utils/*"
  - "openmls/tests/utils/mls_utils/*"
